// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/**:all': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/[...all]').default>>>>
    }
    '/api/customers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/index').default>>>>
    }
    '/api/groceries': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceries/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groceries/index.post').default>>>>
    }
    '/api/habits': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/habits/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/habits/index.post').default>>>>
    }
    '/api/health/fasting': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health/fasting.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health/fasting.patch').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health/fasting.post').default>>>>
    }
    '/api/health/measurements': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health/measurements.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health/measurements.post').default>>>>
    }
    '/api/health/workout': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health/workout.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health/workout.post').default>>>>
    }
    '/api/mails': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mails/index').default>>>>
    }
    '/api/music/file': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/music/file.delete').default>>>>
    }
    '/api/music/file/**:key': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/music/file/[...key].get').default>>>>
    }
    '/api/music': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/music/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/music/index.post').default>>>>
    }
    '/api/music/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/music/upload.post').default>>>>
    }
    '/api/notes/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id].put').default>>>>
    }
    '/api/notes/batch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/batch.post').default>>>>
    }
    '/api/notes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/index.post').default>>>>
    }
    '/api/notes/labels/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/labels/[id].delete').default>>>>
    }
    '/api/notes/labels': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/labels/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/labels/index.post').default>>>>
    }
    '/api/notes/trash': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/trash.get').default>>>>
    }
    '/api/notifications': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/index').default>>>>
    }
    '/api/pages/:type/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/[type]/[slug].get').default>>>>
    }
    '/api/pages/find/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/find/[slug].get').default>>>>
    }
    '/api/pages/id/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/id/[id].delete').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/id/[id]').default>>>>
    }
    '/api/pages/id/:id/versions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/id/[id]/versions.get').default>>>>
    }
    '/api/pages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/index.post').default>>>>
    }
    '/api/pages/versions/:versionId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/versions/[versionId].get').default>>>>
    }
    '/api/pages/versions/:versionId/approve': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/versions/[versionId]/approve.post').default>>>>
    }
    '/api/pages/versions/:versionId/revert': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/versions/[versionId]/revert.post').default>>>>
    }
    '/api/pets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pets/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pets/index.post').default>>>>
    }
    '/api/projects/boards/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/boards/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/boards/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/boards/[id].put').default>>>>
    }
    '/api/projects/boards': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/boards/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/boards/index.post').default>>>>
    }
    '/api/projects/cards/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/cards/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/cards/[id].put').default>>>>
    }
    '/api/projects/cards': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/cards/index.post').default>>>>
    }
    '/api/projects/fields/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/fields/[id].delete').default>>>>
    }
    '/api/projects/fields': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/fields/index.post').default>>>>
    }
    '/api/projects/lists/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/lists/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/lists/[id].put').default>>>>
    }
    '/api/projects/lists': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/lists/index.post').default>>>>
    }
    '/api/watchlist': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/watchlist/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/watchlist/index.post').default>>>>
    }
    '/ws/visitors': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/ws/visitors').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/sitemap_index.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap_index.xml').default>>>>
    }
    '/__sitemap__/**:sitemap': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap/[sitemap].xml').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap.xml').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/robots/dist/runtime/server/routes/robots-txt').default>>>>
    }
    '/__og-image__/font/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-og-image/dist/runtime/server/routes/font').default>>>>
    }
    '/__og-image__/image/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/__og-image__/static/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
  }
}
export {}