/**
 * Master Public Key for Key Escrow.
 * This allows administrators to recover employee data in case of
 * offboarding or audits.
 */
export const MASTER_PUBLIC_KEY = `-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEaX96mhYJKwYBBAHaRw8BAQdAPCRXpNcxhV3CTp6ey7L74htkn3u8W+cM
RIxdEpIMEpHNMVJpbWVsaWdodCBFbnRlcnRhaW5tZW50IDxyaW1lbGlnaHRA
cmltZWxpZ2h0LmNvbT7CwBMEExYKAIUFgml/epoDCwkHCRAHPpA28vABPUUU
AAAAAAAcACBzYWx0QG5vdGF0aW9ucy5vcGVucGdwanMub3Jn/EpZ+NzNaN7J
vT23urj/lQ12t3YRMwUugHVMbMWzy1AFFQoIDgwEFgACAQIZAQKbAwIeARYh
BFn5kloR/C8u8t4uQQc+kDby8AE9AADstAEAy5Fl3061jtQ1M2Sz7h4fyD1z
8Xyb013aoy8iRY1sqgEBAIPs0W9vxank/mwsnZaqRBUcyNSACwWnchhSa8Bh
CeYIzjgEaX96mhIKKwYBBAGXVQEFAQEHQEOpxSTbUgWJXRfEO6wwobJHzote
M4VudgMpJu7ViMNGAwEIB8K+BBgWCgBwBYJpf3qaCRAHPpA28vABPUUUAAAA
AAAcACBzYWx0QG5vdGF0aW9ucy5vcGVucGdwanMub3JnCXVAkkeUtTPwhMT+
fu6Rdo+6T14rPk0wU4pBE1hOXJ8CmwwWIQRZ+ZJaEfwvLvLeLkEHPpA28vAB
PQAAwyEA/1OwjpBItH+k9lzJw5bwpVch9kMtJVWavcjd7YInueP4AQCn4QHI
5LsMXxf3S3LJcodx5GwGPgncFbciR5IGjuyOCw==
=whvH
-----END PGP PUBLIC KEY BLOCK-----`;
