// Generated by rimelight-components Nuxt Module
import { Component } from 'vue'
export declare const BLOCK_EDITOR_COMPONENT_MAP: { [key: string]: () => Promise<{ default: import("vue").Component }> | undefined }
export declare const CalloutBlock: () => Promise<{ default: import("vue").Component }>
export declare const CardBlock: () => Promise<{ default: import("vue").Component }>
export declare const ImageBlock: () => Promise<{ default: import("vue").Component }>
export declare const ParagraphBlock: () => Promise<{ default: import("vue").Component }>
export declare const SectionBlock: () => Promise<{ default: import("vue").Component }>
