name: Move Open Issues to Next Iteration

on:
  # Schedule the job to run automatically.
  # This example runs "at 05:00 UTC, only on Monday"
  # You can adjust the cron schedule as needed (e.g., '0 0 * * *' for midnight daily).
  schedule:
    - cron: "0 5 * * 1"

  # Allow manual trigger from the GitHub Actions tab for testing or immediate use.
  workflow_dispatch:

jobs:
  move_to_next_iteration:
    name: Automate Iteration Move
    runs-on: ubuntu-latest

    steps:
      - name: Move Issues and PRs to Next Iteration
        uses: blombard/move-to-next-iteration@v0.6.1
        with:
          owner: ${{ github.repository_owner }}
          number: 1
          token: ${{ secrets.PROJECT_PAT }}
          iteration-field: Iteration
          iteration: last
          new-iteration: next
          excluded-statuses: "Done,Canceled,Won't Fix"
